### ISSUE TITLE
[BUG] PS-M not showing as working in InfoBar in TX

### ISSUE THREAD

**Issue by sjk7** [sjk7/Thetis-2.9.0#16]
**NOTE TO SELF**

PureSignal Manual is not showing status correctly in infobar during transmit.

**Comment by DD8JM** [comment]
When I switch from PS-A to PS-M the first time the feedback value is displayed, then the second time it is not displayed anymore. I don't find it disturbing because it is a single calibration and the same feedback value is taken.

![2023-04-18_19h50_15](https://user-images.githubusercontent.com/47968792/232862973-f5639149-8c24-477b-8ad5-f1c7f451aa97.jpg)

![2023-04-18_19h50_34](https://user-images.githubusercontent.com/47968792/232863022-002bfd58-88a1-4205-9319-d46105c4e24a.jpg)

**Comment by sjk7** [comment]
@DD8JM Sure. This makes sense. However, I'd like some indication in the infobar. I did code it, but it isn't showing at the moment. I like this PS-M mode because there is a bug in HL2 somwhere where PS-A freaks the audio out, very randomly. Its sounds like 'The Voice Of The Mysterons'. This doesn't happen with a manual calibration. I hope you also find PS-M useful

**Comment by DD8JM** [comment]
This is not unique to HL2, it runs through all devices and has been present in PowerSDR, PS2-A sporadically, for some unexplained reason, produces a picket fence of signals. Because of this some LDMOS transistor amplifiers with a BLF188XR already died.

With Singel calibration this does not happen, I think it is because of the SATT, which I do not have in my setup (Red Pitaya) but a manual SATT and I do not have these problems.

**Comment by sjk7** [comment]
@DD8JM Joerg:

Now this is interesting. I have never been able to find this bug as it is sooo random (apparently) and may only happen once in a busy QSO evening. What a shame if it can destroy 200 dollars' worth of LDMOS. :-( Bummer. I'm glad you told me that, as I am currently building an amp based on a MRF1k80H.

If it's this bad, I may have to add an option to _only_ permit Single cal. Because that is an expensive consequence!

Steve

**Comment by DD8JM** [comment]
@Steve:
Whether Warren knows about this I can't say, in my environment there are some OM's who have changed their power amps with a BLF188 to insensitive transistors after changing several transistors. You often see signals on the band like a picket fence, then you know PS-A is freaked out. This affects both Anan and Hermes transceivers. Maybe you can find the problem. Thanks for your work, for us amateur radio operators. Apache Labs should have provided you with an Anan by now, if they can do their business with the help of people like you and Richie and the many others.

**Comment by RdWing** [comment]
Do we have any screencaps of PS "freaking out"? With good samplers and proper sampling levels being delivered it's been a long time since I've seen PS working incorrectly anywhere.

**Comment by DD8JM** [comment]
@RdWing
Screen shots I don't have of them, as samplers were used at two OM's where the BLF's died, these samplaer:
[](https://preciserf.com/shop/hfs-1-5/)

Both have Hermes boards with PowerSDR in use.

I also use this sampler in my setup with a Red Pitaya without problems, but also without SATT.

**Comment by RdWing** [comment]
@DD8JM That's likely part of the problem. -30dB sampling factor is likely delivering too much sampled signal back to the Hermes. With a -30 dB sampler you must use an attenuator depending on your power level.

Rather I much recommend using something like a -55 dB sampler which provides the right returned sample level for power levels from barefoot-1500w.

Also on Hermes you must be careful with crosstalk on the sample return line.

**Comment by DD8JM** [comment]
I have with me still a controllable attenuator of 30db installed. The SATT makes at Hermes and ANAN 31db.
The feedback display would also always blue at too much level. This is not the reason that PS-A sporadically does not regulate and generates peaks and signals over a wide spectrum.

**Comment by sjk7** [comment]
Can confirm it just randomly "freaks' as you go into TX mode. Once it does it, you to rekey, and it will normally clear it. But not always. Can also confirm this happens when the feedback is green.

**Comment by sjk7** [comment]
I should mention that PS-M is not the same as 'single' calibration in that PS-M inherits directly its settings from PS-2. This is why the button cylces PS-A -> PS->M -> no ps (off).

Assuming you have  'green' Puresignal on PS-A, cycling the switch to PS-M remembers exactly the profile secured by PS-A. It does NOT do a single calibration here, it simply continues to use the 'green' PS-A setting.

If you were in RX when you cycle back to PS-M then it should behave as if it were a single calibration.

Steve

**Comment by DD8JM** [comment]
@sjk7 
Thanks Steve, I thought it would do another calibration and then save the value.

Greetings Jörg

**Comment by sjk7** [comment]
Email from another ANAN user today:
"You have helped me get my 10 E working with PS"
You have also helped a friend out who had a 200D with "micro voice glitching"

Of course there could be a million reasons why PS-A is not working for these people (not enough cpu power, say) but I would really like to get to the bottom of this one, properly

Steve

**Comment by w-u-2-o** [comment]
Hi folks, Steve asked me to swing by and take a look at this issue. Disclaimer: I'm an Apache labs hardware owner (100D, borrowed a 200D for a while, 8000DLE) and experienced openHPSDR user. I've been a part of the community for many years and have lived through the entire evolution and development of PureSignal. I started and administer the Apache Forum.

Summary:

The effort to modify Thetis to satisfy the issues HL2 folks are having look to be Band-Aids on a more fundamental problem, and that problem is very, very unlikely to be any bugs in WDSP or Thetis given their stable performance on Apache hardware loaded with openHPSDR firmware. The aberrant picket fence waveform is almost always caused by a corrupted or otherwise bad RF feedback signal. It can also be caused by firmware problems where the data from the feedback DDC is corrupt or if the delay paths in the firmware are not correct. Areas that should probably be carefully looked at by any HL2 user having a problem with PureSignal are

- Contamination of the feedback signal with the transmitted signal
- Feedback signal levels at the input to the HL2 receiver
- How attenuation is accomplished during PureSignal  (full duplex) receive in the HL2 design (and I admit my ignorance here)
- How stable the PureSignal DDC and delay timings are in the HL2 firmware.

In more detail:

On newer Apache hardware (200D and newer), given proper RF feedback levels PureSignal is unambiguously stable. There are no bugs that anyone is aware of in either WDSP, the last version of PowerSDR mRX PS, or any recent version of Thetis. It is extraordinarily unlikely that the problems that some HL2 users are experiencing have anything to do with WDSP or Thetis.

On older Apache designs (100D and older) RF crosstalk (poor isolation) inside the main RF unit (not in an external amplifier) between the transmitted signal and the RF feedback path is a significant problem and often caused these "picket fence" or "comb" issues. With weak feedback levels PureSignal performance does suffer on these units. I'm honestly not at all familiar with the HL2 world, but it seems that build quality and methods to route signals may vary widely. It is extremely important to ensure good isolation between these signal paths. Many Apache owners modified their early units (myself included) to improve isolation to eliminate this problem.

Another very concerning theme in the discussion above seems to be a lack of understanding as to what appropriate feedback signal levels are. First and foremost they need to be less than whatever level might physically damage the HL2. I took a look at the schematic, and it appears that a practical, safe maximum is probably less than +10dBm. No doubt you folks know better than I. So if you've got a 60dBm (1KW) amp you better have a feedback path (coupler + attenuation) that is at least -50dB.

After that, there does not appear to be a digitally controlled step attenuator as part of the design (or is there some modification or external board people are using?) Without a digitally controlled step attenuator, which is a very key piece of the PureSignal design, I can only guess that there is some attempt to emulate this using the programmable front end amplifier gain on the AD9866. Is that correct? This seems like it might be problematic. I'd like to understand more about how this is implemented in the HL2 design. I suppose if the normal gain setting is 20dB then there would be 32dB of attenuation dynamic range (the data sheet says the gain can be programmed as low as -12dB). Please advise how RF gain/loss is controlled in the HL2, especially with respect to PureSignal. Until I understand that it is hard to weigh in further on this area. However, prior to auto-attenuate the Apache hardware community saw that nasty picket fence all the time. People had great difficulty adjusting their attenuators manually (not sure why, but they did!) PureSignal feedback levels must be kept "in the green". I'm not at all familiar with the HL2 RF cascade, but on Apache hardware that means no higher than +3dBm at the ADC input. Who can tell me what range of RF feedback levels at the HL2 receiver input connector result in a green feedback level indication, min. level and max. level and with what AD9866 gain setting?

Finally, one must consider the performance of the HL2 firmware. As I already wrote above, for modern Apache hardware the firmware has evolved to be unambiguously stable. On older hardware (again, 100D and prior) the so-called "Protocol 2" firmware is not nearly as reliable and thus it is not unusual to see the problems you are reporting in this issue. And before someone starts quoting Apache Forum posts about crappy firmware on more recent hardware like the 7000's, know that these problems are associated with failure to close timing on the GigE interface, NOT anything to do with PureSignal. The PureSignal firmware was carried over wholesale from Protocol 1, which remains unambiguously stable on all Apache hardware types.

73,

Scott/w-u-2-o

**Comment by sjk7** [comment]
Thanks Scott, I would love to get to the bottom of it. It is not finger trouble (though my UI bugs certainly are!), sampling quality or user issues, at least on my part. It is something like a data race which will only show under certain conditions, even in the lab here.

Since it works, say 99 times out of 100 ( I wish it were this predictable) then it is definitely some kind of obscure bug, Where it is I don't know. I am only pointing the finger as wdsp **because this did not happen in the very early code the mrx-ps versions at all.**

I cannot rule out a timing issue in the firmware, but why, then it works 999/1000 (say) and not the 1 or 0.1% the rest of the time?
I have tried delaying the onset of PS anything from ms to actual seconds, but the only currently workaround is to take a known good snapshot from PS-A and store this for the QSO session. Single cal is no good for this use-case. It's all we have until someone, somewhere works this one out. Crosstalk or operator error is not a factor, otherwise I would expect to see this happening a lot more often.

It is _very_ intermittent. It's ripe for the UX writer to blame the actual PS code, ripe for the PS code to blame the hardware and so on, but this will not get the issue fixed. All parties need to have a big push to resolve it.

I don't think anyone can claim either the Anan radios nor the wdsp is flawless. I have fixed several bugs in it. One was quite a serious deadlock which meant under certain conditions the radio would be left 'hanging' and had to be reset. One does not want to provoke some kind of "poor vs rich" as in Anan users vs HL2 users. The whole point of my project here is to unify the two, but this will mean give and take on both sides.

For example I "lost" when I had to add another checkbox for making the volume work properly on VAC. Apparently some digital anan users "wouldn't like this". So I changed the code. It needs changing badly in some respects. But sometimes you simply won't get what you want, as someone (me :-( ) has to make informed design decisons to move the project forward.

I certainly do not see the the console especially as an unchangeable, immutable, brilliantly designed bit of work. It is a very big muddle, and my ambition here is to simplify and unify its use, and actually make the code more accessible to those whose first and only language is C Sharp for further development. (I am a C++ developer for a day job, and so I intend to participate in the code devlopment, but I certainly don't want to do this for the next 10 years!). 

I realise people want to have  "grandfather rights" to how things used to work, but  they are welcome to run an older, unmaintained version if that's what they want to do and I really can't marry the interfaces.

I say again, it broke sometime after of PowerSDR mRX PS (because it is 100% reliable over there), and before Thetis came on the scene, contrary to what you state above. If I could use that code in Thetis instead, I would. But it's an embyonic version of wdsp in there, with lots of unneccessary callbacks and context switches, which is no good for VAC voice. However, if push comes to shove and with a LOT of work, I can find what is different about PS in mRX and sort it. 

But I am hoping that is not necessary as I have really done all I can as far as auditing wdsp myself. It probably needs an expert eye. And just as this revision of Thetis has made gigantic progress in now being able to use the maintaned, current portaudio (and not some heavily modified thing dated years ago), then I would also like to use the current, supported wdsp and friends in this app, not something I cobbled together from old code!

By the way, all the information you requested we already have (and probably more). But I don't have to repeat the measurements and conclusions actually documented on the web and freely available. Hint: a german ham @ https://dl1ycf.darc.de/hl2.htm .I can confirm what he says, more or less, from the lab readings here. 

The HL2 has a variable attenuator in sofware that is adjusted by PS-A continuously. It's using the same code you are using today.

**Comment by sjk7** [comment]
To sum up, I am always willing to re-open issues that are closed. But I need to know I will have the time to deal with it. Currently Single cal is not only inconvenient to use (its on the Linearity window) but it is practially useless if it only works on that exact transmission. (one-shot single cal mode). It will get sorted but there are some egregious bugs ahead of it. Basically if something is crashing the app, the priority is huge, which is why I spent all day finding a buffer overrun in ChannelMaster the other day.

There are also some bugs reported by good people, and in one case in particular, I have not fixed any of them for him! So I intent to deal with that one the next time I get spare time. I don't want to reward good feedback by doing nothing about it!

**Comment by w-u-2-o** [comment]
I understand bug fix priorities.

The single cal function is not at all useless. People have been using it
for years, myself included.

As you wrote previously, you have accidentally conflated single cal with
the desire to transition from an automatic/continuous mode to a
static/manual mode. Several suggestions have been made on how to divorce
that action from the single cal button so that single cal can return to its
originally intended function. I'll add another: rather than add buttons as
previously suggested, change the Linearity menu so when it pulls down you
have an "Enabled" checkbox and an option called "Settings" to bring up the
PureSignal setting window. That way the OFF function can be removed from
the PS-x button on the main console and HL2 users can bounce back and forth
between auto and manual just by clicking that button without having to go
through OFF. And single cal goes back to doing what it used to do. Or,
finally, just make them roll through the OFF state. Either way, people
would like their single cal button back.

Again, I fully understand the motivations for this coming from the HL2
community. I hope to be able to assist in fixing the underlying issue so
that "PS-M" is no longer required, although once it's in the software
there's no point in taking it back!

Thanks,

Scott

**Comment by sjk7** [comment]
I am closing this as it is now effectively out of date until I can rework "PS-M"

Steve
